### ISSUE TITLE
Monitor (delegates): Forging time fails for the delegate who is forging and it doesn't update

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-desktop#2663] opened 2019-11-22 09:39 UTC
1.23.0-rc1

The application fails to get the "forging time" from delegates who are forging a block the moment you go to monitor -> delegates. 

If it's a wanted behaviour then it shouldn't show a `-` but sth. like `now` or `forging now`. Anway it doesn't update and stays at `-`, so this needs to be fixed.

![grafik](https://user-images.githubusercontent.com/19614645/69415110-49fc4d00-0d14-11ea-91c3-c9ee2ebfc40d.png)

**Comment by slaweet** [comment] 2019-11-22 10:44
I think the problem is that we can get only 100 items from the nextForgers API. IMO the fix shouldbe to change the api to allow limit=101 and then update it here: 
https://github.com/LiskHQ/lisk-desktop/blob/2bc7a4ea6112d843824f55931a8702137736472e/src/components/screens/monitor/delegates/withForgingStatus.js#L70-L72

**Comment by slaweet** [comment] 2019-11-22 11:09
It is happening because getNextForgers can return only 100 delegates. So it's missing in:
https://github.com/LiskHQ/lisk-desktop/blob/2bc7a4ea6112d843824f55931a8702137736472e/src/components/screens/monitor/delegates/withForgingStatus.js#L70-L72

A quick fix would be to do an additional request to fetch more.

A smarter fix would be to find the missing delegate in the delegates list and put that delegate at the end of forgers. 

Talked about it with @reyraa and we came to the conclusion: @colado please fix this with the smarter fix in https://github.com/LiskHQ/lisk-desktop/pull/2641

**Comment by reyraa** [comment] 2019-12-17 14:13
This is fixed by #2624

**Closed by reyraa** 2019-12-17 14:13 UTC
Labels: severity: low, type: defect
