### ISSUE TITLE
Trezor T doesn't work

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-desktop#2449] opened 2019-09-13 19:41 UTC
I tried different things. Restarted Lisk Hub with Trezor connected and without Trezor connected and connected it after Hub started and I clicked "Sign in with a hardware wallet". Everytime nothing happens and I only see this:

![grafik](https://user-images.githubusercontent.com/19614645/64890139-362acf80-d66f-11e9-9eee-600fbf8be0e5.png)

Windows 10, latest Hub, latest Trezor T firmware.

**Comment by hitobb** [comment] 2019-09-23 07:16
I think it may be the problem about Trezor T firmware.

I confirmed that Trezor works fine with this combination.
 - Lisk Hub: 1.21.0-rc.1
 - Trezor T firmware: v2.1.5
 - OS:Windows 10 home 64bit

When you sign in to the Trezor beta wallet site, you can install the latest firmware: v2.1.5.

[github]
https://github.com/trezor/trezor-wallet

[beta wallet site]
https://beta-wallet.trezor.io/next/

Please check this.
Thanks.

**Comment by sridharmeganathan** [comment] 2020-01-15 09:54
I retested this and it is not working in my laptop but it is working in Yashar laptop. We need to identify what could be the reason to close this issue.

**Comment by hitobb** [comment] 2020-03-16 06:59
I came up with one idea to solve this problem.
Are the following software installed on the laptop where Trezor operation cannot be confirmed?

https://wiki.trezor.io/Trezor_Bridge

https://wallet.trezor.io/#/bridge

After summer 2019
Trezor will not work properly if Trezor_Bridge is not installed．
Please check your installed softwares.

I wish this was the cause for why it was failing.
Thanks.

**Comment by reyraa** [comment] 2020-04-29 10:23
I can't reproduce this. Not on Windows nor on Catalina. seems like this works fine with latest changes. I assume it's fixed since then. @punkr0ck Can you please confirm?

**Comment by punkr0ck** [comment] 2020-04-29 12:23
I can confirm that I hadn't this issue again.

But please fix [this](https://github.com/LiskHQ/lisk-desktop/issues/2864).
No one who updated to latest Trezor firmware can access their LSK anymore.
Thanks!

**Comment by reyraa** [comment] 2020-05-04 07:34
@punkr0ck Thank you. I'll fix that one too.

**Closed by reyraa** 2020-05-04 07:34 UTC
Labels: priority: high, severity: high, type: defect
