### ISSUE TITLE
News feed - Don't show twitter replies

### ISSUE THREAD

**Issue by Korben3** [LiskHQ/lisk-desktop#3549] opened 2021-05-16 14:26 UTC
### Description

When users enter the dashboard in Lisk desktop a News feed is present consisting of Twitter and the official blog. I recommend only showing tweets from @LiskHQ and ignoring replies from this account. Or switching to the blog content as default.

### Motivation

Replies are usually very short, and also showing replies does not provide any news to the lisk desktop user. See the screenshot.

![image](https://user-images.githubusercontent.com/42899281/118400645-c5696100-b662-11eb-84f1-cb0d98904233.png)

Please change this in code instead of making Miguel to stop replying 😊 he's great!

### Additional Information

Version 2.0.0-beta.2

**Comment by reyraa** [comment] 2021-05-26 08:42
@Korben3 Thank you for reporting this issue. Lisk Service team will resolve this problem. Once the issue is resolved by Lisk Service, your installed version of Lisk Desktop should work out of the box.

**Closed by reyraa** 2021-05-26 08:42 UTC
Labels: type: bug
