### ISSUE TITLE
2.3.0 beta.0: UI bug when creating a new account

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#4195] opened 2022-03-06 22:11 UTC
Windows 11
resolution: 2560x1440 

![image](https://user-images.githubusercontent.com/1260700/156944215-44b62b0e-c8e6-42dd-945f-94c623be1491.png)

**Comment by ikem-legend** [comment] 2022-03-09 11:45
Duplicate of [#4181](https://github.com/LiskHQ/lisk-desktop/issues/4181) closed by the PR [#4189](https://github.com/LiskHQ/lisk-desktop/pull/4189)

**Closed by ikem-legend** 2022-03-09 11:45 UTC
Labels: type: bug
