### ISSUE TITLE
Send LSK transaction fee is always 0

### ISSUE THREAD

**Issue by isalga** [LiskHQ/lisk-desktop#3232] opened 2020-12-16 10:37 UTC
### Expected behavior
Should calculate transaction fees correctly

### Actual behavior
Transaction fee is always 0

### Steps to reproduce
- Log in
- Go to walet
- Click send LSK

### Which version(s) does this affect? (Environment, OS, etc...)
`2890-support-sdk-4`

**Comment by UsamaHameed** [comment] 2020-12-16 12:35
@isalga I was not able to reproduce this issue. Let me know if you can reproduce this in which case, we will work on it.

**Comment by UsamaHameed** [comment] 2020-12-17 10:00
Closing this for now as I can't reproduce this.

**Closed** 2020-12-17 10:01 UTC
Labels: type: bug
