### ISSUE TITLE
Incorrect number of voters in "Delegate profile"

### ISSUE THREAD

**Issue by Korben3** [LiskHQ/lisk-desktop#3763] opened 2021-09-01 21:21 UTC
### Expected behavior

Display correct number of voters for the delegate.

### Actual behavior

The maximum number of voters shown is always 10.

![image](https://user-images.githubusercontent.com/42899281/131746227-a1094eee-e90f-48b7-8459-abe312aa71ef.png)

For example minions has 45 voters at moment of writing: https://liskscan.com/account/lsk9m2skmpt5zec7kdybwqabe2zmkdmekt7uupq8w

### Steps to reproduce

Select an active delegate and goto the delegate profile

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

**Comment by ManuGowda** [comment] 2021-09-07 09:51
This issue is duplicate of https://github.com/LiskHQ/lisk-desktop/issues/3769 
It will be addressed as part of PR https://github.com/LiskHQ/lisk-desktop/pull/3771

**Closed by ManuGowda** 2021-09-07 09:51 UTC
Labels: type: duplicate
