### ISSUE TITLE
Can not update 1.27.1 to 1.27.2 on Windows 10

### ISSUE THREAD

**Issue by hitobb** [LiskHQ/lisk-desktop#3374] opened 2021-02-11 15:55 UTC
### Expected behavior

I want to update 1.27.1 to 1.27.2.

### Actual behavior

I can not to update 1.27.1 to 1.27.2.

### Steps to reproduce

click the update now on "This version fixes a number of issues in the hardware wallet support. Update now or Read more."

After few minuets. this message is appear. 

<img width="420" alt="キャプチャ0001" src="https://user-images.githubusercontent.com/14948578/107661656-d190fb80-6ccc-11eb-89cc-45a06f8c9acd.PNG">

<img width="421" alt="キャプチャ0002" src="https://user-images.githubusercontent.com/14948578/107661710-dfdf1780-6ccc-11eb-8157-e60b7ca8b0af.PNG">

### Which version(s) does this affect? (Environment, OS, etc...)

<img width="381" alt="キャプチャ0003" src="https://user-images.githubusercontent.com/14948578/107661801-f7b69b80-6ccc-11eb-94c4-6d3c11bd17e2.PNG">

**Comment by UsamaHameed** [comment] 2021-02-12 11:55
Thanks for reporting the issue @hitobb. We will take a look and fix asap.

**Comment by UsamaHameed** [comment] 2021-02-15 12:01
Hello @hitobb, we have looked at the issue and tested using several devices. We were not able to reproduce the issue on our end. Please try to do a manual install; since it is very likely that you have the application that was released with the incorrect signature. We had hot updated the release assets later with the correct signatures. Please let me know if you still come across the issue.

**Closed by UsamaHameed** 2021-02-15 12:01 UTC
Labels: type: bug
