### ISSUE TITLE
Trezor T: Entering Passphrase on host doesn't work (Hidden Wallets)

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-desktop#2214] opened 2019-07-03 11:48 UTC
- Trezor T, Firmware 2.1.1
- Lisk Hub 1.18.1
- Windows 10 Pro, Version 1809, Build 17763.592

I use hidden wallets on Trezor T. That means, you have to enter a PIN and then a Passphrase. You have the option to enter the passphrase on the Trezor itself (Device) or on the host device (Host). If I tap on "Host" nothing happens. No pop up window where I can enter the passphrase. I also tried typing the passphrase on the keyboard to check if it's working. It's not. Of course it's safer to enter the passphrase on your Trezor device but Hub should also support the "host"-option.

Related: #2864

**Comment by hitobb** [comment] 2019-07-16 15:57
- Trezor T, Firmware 2.1.1
- Lisk Hub 1.19.0-rc.1
- Windows 10 Home 1903 build 18362.239

I also confirmed the same behavior.
I hope this enhancement is added.

**Comment by reyraa** [comment] 2021-06-28 14:58
Duplicate of #2864.

**Closed by reyraa** 2021-06-28 14:58 UTC
Labels: type: duplicate
