### ISSUE TITLE
Transactions page does not update automatically

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#5479] opened 2023-11-22 17:10 UTC
Lisk Desktop v3.0.0-rc.5

I claimed my rewards but the transaction doesn't show up automatically. Additionally the notification that I have unclaimed rewards shows up again after a while. the transaction is now 5 minutes ago and it is visible on Liskscan Explorer.

It only updates if I switch from "Wallet" to "Applications" for example in the menu and back to "Wallet" but it should update by itself.

Transaction on Liskscan:
![image](https://github.com/LiskHQ/lisk-desktop/assets/1260700/2a131aba-4089-4e15-b0fc-4af0d1cbeafa)

Screenshot after I claimed my rewards:
![image](https://github.com/LiskHQ/lisk-desktop/assets/1260700/46267c6d-a8fa-486c-8f52-6e71a43ba425)

**Comment by ManuGowda** [comment] 2023-11-22 17:18
This is been looked into by service and sdk team to fix this issue, it should be resolved with backend changes.

**Comment by sameersubudhi** [comment] 2023-11-22 18:06
The issue is with Lisk Service and is already resolved with https://github.com/LiskHQ/lisk-service/issues/1930.

**Comment by ManuGowda** [comment] 2023-11-22 18:07
Thanks sameer for response, closing the issue as its resolved by Lisk Service.

**Closed as completed by ManuGowda** 2023-11-22 18:07 UTC
Labels: status: wontfix
