### ISSUE TITLE
Adopt voting flow according to new design

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-desktop#4425] opened 2022-08-01 14:21 UTC
### Description

- Implement new [design](https://www.figma.com/file/9JbvSmtLNJIttXp68uhmQR/Change-API-to-support-Lisk-SDK-v6-API?node-id=98%3A16082) changes for voting domain
  - Update delegates page to show 
    - Summary on hover (mini profile)
    - Allow to add votes
  - Update Add voting modal
  - Update Edit voting modal

### Acceptance Criteria

- Users should be able to add/edit vote for a delegate from delegate domain or mini profile
- User should be able to see warning for punished delegate
- Add/Update required unit tests

**Comment by sridharmeganathan** [comment] 2022-09-27 11:42
Duplicate of #4466

**Closed as completed** 2022-10-10 13:45 UTC
Labels: type: improvement
