### ISSUE TITLE
TransactionStatusFail image is not loaded

### ISSUE THREAD

**Issue by endro42** [LiskHQ/lisk-desktop#5059] opened 2023-05-31 14:01 UTC
### Expected behavior

When scrolling through transactions, you'd expect that the icons for failed or success will always be loaded

### Actual behavior

The status for transaction failed shows a broken image

<img width="177" alt="image" src="https://github.com/LiskHQ/lisk-desktop/assets/12698415/50599efd-2901-49b9-92d0-8cb564fd19f9">

### Steps to reproduce

Create a failed transaction or view "endro" profile on betanet

**Comment by ManuGowda** [comment] 2023-06-01 07:31
Duplicate of https://github.com/LiskHQ/lisk-desktop/issues/5042

**Closed as completed by ManuGowda** 2023-06-01 07:31 UTC
Labels: type: duplicate
