### ISSUE TITLE
Web socket still breaks after a couple of interactions with the app

### ISSUE THREAD

**Issue by eniolam1000752** [LiskHQ/lisk-desktop#5451] opened 2023-11-15 16:09 UTC
### Expected behavior
- Web socket connection should not break after large amount of interactions

### Actual behavior
I get this error after a lot of interactions with multi-signature transactions

![image (4)](https://github.com/LiskHQ/lisk-desktop/assets/32064769/d338017d-86b0-4591-9fc2-f73e946f4123)

**Comment by przemerr** [comment] 2023-11-15 16:13
i think it's a duplicate of https://github.com/LiskHQ/lisk-desktop/issues/5428 😇 unless it's still happening after the fix

**Comment by ManuGowda** [comment] 2023-11-21 15:49
We made a fix with 5428, its not reproducible at the moment. We will close this issue after validating few more times.

**Comment by ManuGowda** [comment] 2023-11-22 18:10
Unable to reproduce the issue with latest release https://github.com/LiskHQ/lisk-desktop/releases/tag/v3.0.0-rc.5

hence closing.

**Closed as completed by ManuGowda** 2023-11-22 18:10 UTC
Labels: status: invalid
