### ISSUE TITLE
Support sign message with HW wallet - Child of #1101

### ISSUE THREAD

**Issue by michaeltomasik** [LiskHQ/lisk-desktop#1318] opened 2018-09-27 10:18 UTC
### Description of the problem

Child of #1101

**Comment by hirishh** [comment] 2018-09-28 15:18
At the moment this is not possible with Ledger (Trezor Model T is ok). There is a bug in the Ledger Lisk App and we are going to fix it. 

I will update this issue when solved.

**Comment by reyraa** [comment] 2020-03-16 12:53
Duplicate of #2757

**Closed by reyraa** 2020-03-16 12:53 UTC
Labels: priority: medium, type: enhancement
