### ISSUE TITLE
Update the script and regenerate the database snapshot

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3454] opened 2021-03-26 12:35 UTC
### Description

Please describe what functionality is needed

### Motivation

Please describe why it is needed

### Acceptance Criteria

Please describe the conditions which must be met for this issue to close

**Comment by UsamaHameed** [comment] 2021-03-26 12:45
Duplicate of #3449

**Closed by UsamaHameed** 2021-03-26 12:45 UTC
