### ISSUE TITLE
Validator staking table should look like design

### ISSUE THREAD

**Issue by oskarleonard** [LiskHQ/lisk-desktop#4751] opened 2023-01-19 17:16 UTC
### Expected behavior
Validator staking table should look like design
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/8784876/213513954-31b35fe1-86d2-41f3-ab3c-cefdd54b70f9.png">

### Actual behavior
<img width="1608" alt="image" src="https://user-images.githubusercontent.com/8784876/213513912-a8722cec-fc02-4c46-b314-ae639276e7f2.png">

### Steps to reproduce
- Select Validators from the side menu
- Select one validator with many stakers (use mock data to force many stakers)

### Which version(s) does this affect? (Environment, OS, etc...)
N/A

**Comment by soroushm** [comment] 2023-01-23 11:04
only we need to check for load more, ui working as intended

**Comment by ManuGowda** [comment] 2023-02-16 13:11
This is a valid behaviour hence closing, once we tag alpha.0 we can conduct QA to find the incorrect behaviour.

**Closed as completed by ManuGowda** 2023-02-16 13:11 UTC
Labels: status: invalid
