### ISSUE TITLE
Downloading the paper wallet in backup account shows different address

### ISSUE THREAD

**Issue by endro42** [LiskHQ/lisk-desktop#5028] opened 2023-05-25 08:49 UTC
### Expected behavior

When downloading "lisk_passphrase_store_safely.pdf", a user should see a wallet address thats that same as the wallet address visible in Lisk Desktop

### Actual behavior

<img width="1004" alt="image" src="https://github.com/LiskHQ/lisk-desktop/assets/12698415/f55dc950-41a8-43cf-95de-4bf97452360e">

![image](https://github.com/LiskHQ/lisk-desktop/assets/12698415/fcc98737-ffc1-49fa-ade9-862967c53664)

### Steps to reproduce

- Click "Backup account" in the submenu of your wallet (top left corner)
- Compare address visible in the wallet with the paper wallet

**Comment by ManuGowda** [comment] 2023-05-25 08:51
Duplicate of https://github.com/LiskHQ/lisk-desktop/issues/5022

**Closed as completed by ManuGowda** 2023-05-25 08:52 UTC
Labels: type: duplicate
