### ISSUE TITLE
Fix regressions introduced to the electron app

### ISSUE THREAD

**Issue by UsamaHameed** [LiskHQ/lisk-desktop#3669] opened 2021-07-02 08:28 UTC
### Expected behavior
The user should be able to quit the application using `cmd+q` and through the `Quit` option in the menu in macOS.

### Actual behavior
The quit option (along with some other options) is not present in the menu and the shortcut does not work. Possible regression of the updates to electron and various other packages.

### Steps to reproduce
Try to quit lisk desktop using cmd+q on macOS.

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Desktop 2.0.0-rc.1 on macOS

**Comment by sridharmeganathan** [comment] 2021-09-20 14:30
Duplicate of https://github.com/LiskHQ/lisk-desktop/issues/3741

**Closed by sridharmeganathan** 2021-09-20 14:30 UTC
Labels: type: duplicate
