### ISSUE TITLE
Add data size to the transaction detasils page

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#2541] opened 2019-10-09 12:10 UTC
### Description
We need to show the size of the data next to the data value. we should show `0bytes` in case the data field is empty.

**Comment by slaweet** [comment] 2020-01-07 13:48
This seems to be duplicate of https://github.com/LiskHQ/lisk-desktop/issues/2514 which was already done in https://github.com/LiskHQ/lisk-desktop/pull/2686

**Closed** 2020-01-07 13:49 UTC
Labels: type: duplicate
