### ISSUE TITLE
Fix auto logout feature

### ISSUE THREAD

**Issue by UsamaHameed** [LiskHQ/lisk-desktop#3395] opened 2021-02-19 14:08 UTC
### Expected behavior
The user should be logged out after they are inactive for a specificied amount of time. 

### Actual behavior
The user is logged out after `login time + specified logout timeout > current time`.

**Comment by sridharmeganathan** [comment] 2021-03-23 09:37
duplicate of #3402

**Closed** 2021-03-23 09:38 UTC
Labels: status: invalid
