### ISSUE TITLE
Resolve HW todos

### ISSUE THREAD

**Issue by isalga** [LiskHQ/lisk-desktop#3903] opened 2021-10-29 08:16 UTC
src/components/screens/lockedBalance/transactionStatus/transactionStatus.js
src/components/screens/votingQueue/result/result.js
src/components/screens/multiSignature/result/result.js
src/components/screens/reclaimBalance/modal/status/status.js
libs/hwManager/index.js

**Comment by ManuGowda** [comment] 2021-11-03 10:46
Duplicate of https://github.com/LiskHQ/lisk-desktop/issues/3661

**Closed by ManuGowda** 2021-11-03 10:46 UTC
